# Generated by Django 4.2.5 on 2023-09-29 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='title',
            new_name='title1',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='body3',
            new_name='title2',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='image3',
        ),
    ]
