# Generated by Django 4.2.5 on 2023-09-29 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_alter_articles_title2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='relatedarticle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webpages.articles'),
        ),
    ]
